=== yuri0r/WiSe17_18_DPUE/src/RechnerAufgabe3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="rechnungen">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="rechnung"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="rechnung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="anschrift-des-leistenden-unternehmers"/>
                <xs:choice>
                    <xs:element ref="steuer-nummer-des-leistenden-unternehmers"/>
                    <xs:element ref="umsatzsteuer-identifikations-nummer"/>
                </xs:choice>
                <xs:element ref="anschrift-des-leistungs-empfängers"/>
                <xs:element ref="rechnungs-nummer"/>
                <xs:element ref="austellungs-datum"/>
                <xs:element ref="verwendete-waehrung"/>
                <xs:element ref="leistungen"/>
                <xs:element ref="entgelt"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="anschrift-des-leistenden-unternehmers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name-unternehmen"/>
                <xs:element minOccurs="0" ref="email-adresse"/>
                <xs:element ref="adresse"/>
                <xs:element minOccurs="0" ref="telefon-nummer"/>
                <xs:element minOccurs="0" ref="fax-nummer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="anschrift-des-leistungs-empfängers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name-leistungs-empfänger"/>
                <xs:element ref="adresse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="austellungs-datum">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag"/>
                <xs:element ref="monat"/>
                <xs:element ref="jahr"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="leistungen">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="leistung"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="entgelt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gesamt-betrag"/>
                <xs:element ref="netto-betrag"/>
                <xs:element ref="mehrwert-steuer-betrag"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresse">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ort"/>
                <xs:element ref="postleihzahl"/>
                <xs:element ref="straße"/>
                <xs:element ref="haus-nummer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="name-leistungs-empfänger">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="vorname"/>
                <xs:element ref="nachname"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="datum">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag"/>
                <xs:element ref="monat"/>
                <xs:element ref="jahr"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="leistung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bezeichnung"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="menge"/>
                    <xs:element ref="einzel-preis"/>
                </xs:sequence>
                <xs:element ref="gesamt-preis"/>
                <xs:element ref="mehrwertsteuer-in-prozent"/>
                <xs:element minOccurs="0" ref="datum"/>
            </xs:sequence>
            <xs:attribute name="position"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="name-unternehmen" type="xs:string"/>
    <xs:element name="email-adresse" type="xs:string"/>
    <xs:element name="ort" type="xs:string"/>
    <xs:element name="postleihzahl" type="xs:string"/>
    <xs:element name="straße" type="xs:string"/>
    <xs:element name="haus-nummer" type="xs:string"/>
    <xs:element name="telefon-nummer" type="xs:string"/>
    <xs:element name="fax-nummer" type="xs:string"/>
    <xs:element name="steuer-nummer-des-leistenden-unternehmers" type="xs:string"/>
    <xs:element name="vorname" type="xs:string"/>
    <xs:element name="nachname" type="xs:string"/>
    <xs:element name="rechnungs-nummer" type="xs:string"/>
    <xs:element name="tag" type="xs:string"/>
    <xs:element name="monat" type="xs:string"/>
    <xs:element name="jahr" type="xs:string"/>
    <xs:element name="bezeichnung" type="xs:string"/>
    <xs:element name="menge" type="xs:string"/>
    <xs:element name="einzel-preis" type="xs:string"/>
    <xs:element name="gesamt-preis" type="xs:string"/>
    <xs:element name="mehrwertsteuer-in-prozent" type="xs:string"/>
    <xs:element name="gesamt-betrag" type="xs:string"/>
    <xs:element name="netto-betrag" type="xs:string"/>
    <xs:element name="mehrwert-steuer-betrag" type="xs:string"/>
    <xs:element name="umsatzsteuer-identifikations-nummer" type="xs:string"/>
    <xs:element name="verwendete-waehrung" type="xs:string"/>
</xs:schema>

=== yuri0r/WiSe17_18_DPUE/src/RechnerAufgabe3.xml
<?xml version = "1.0" encoding ="UTF-8"?>
<!--matrikel-nummer 57099%7 = 0 =>: Ein Pattern fuer eine E-Mail.-->
<rechnungen
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="RechnerAufgabe3.xsd">

    <rechnung>
        <anschrift-des-leistenden-unternehmers>
            <name-unternehmen>Kleintier Meier GmbH</name-unternehmen>
            <email-adresse>klein.meier@tiere.de</email-adresse>
            <adresse>
                <ort>Machthausen</ort>
                <postleihzahl>81828</postleihzahl>
                <straße>Meierring</straße>
                <haus-nummer>3</haus-nummer>
            </adresse>
            <telefon-nummer>077987987</telefon-nummer>
            <fax-nummer>0777987789</fax-nummer>
        </anschrift-des-leistenden-unternehmers>
        <steuer-nummer-des-leistenden-unternehmers>8812382822</steuer-nummer-des-leistenden-unternehmers>
        <anschrift-des-leistungs-empfängers>
            <name-leistungs-empfänger>
                <vorname>Sybille</vorname>
                <nachname>Sonder-Suttelrau</nachname>
            </name-leistungs-empfänger>
            <adresse>
                <ort>Siedelsuderstadt</ort>
                <postleihzahl>77070</postleihzahl>
                <straße>Am Süttelbach</straße>
                <haus-nummer>17</haus-nummer>
            </adresse>
        </anschrift-des-leistungs-empfängers>
        <rechnungs-nummer>657321</rechnungs-nummer>
        <austellungs-datum>
            <tag>15</tag>
            <monat>1</monat>
            <jahr>2017</jahr>
        </austellungs-datum>
        <verwendete-waehrung>euro</verwendete-waehrung>
        <leistungen>
            <leistung position="1">
                <bezeichnung>Antike Holzwürmer</bezeichnung>
                <menge>100</menge>
                <einzel-preis>1.50</einzel-preis>
                <gesamt-preis>150.00</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
                <datum>
                    <tag>1</tag>
                    <monat>1</monat>
                    <jahr>2017</jahr>
                </datum>
            </leistung>
            <leistung position="2">
                <bezeichnung>Holzwurmfutter</bezeichnung>
                <menge>1</menge>
                <einzel-preis>34.45</einzel-preis>
                <gesamt-preis>34.45</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
                <datum>
                    <tag>12</tag>
                    <monat>1</monat>
                    <jahr>2017</jahr>
                </datum>
            </leistung>
            <leistung position="3">
                <bezeichnung>Steinlaus Petrophaga lorioti</bezeichnung>
                <menge>1</menge>
                <einzel-preis>777.77</einzel-preis>
                <gesamt-preis>777.77</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
                <datum>
                    <tag>12</tag>
                    <monat>1</monat>
                    <jahr>2017</jahr>
                </datum>
            </leistung>
        </leistungen>
        <entgelt>
            <gesamt-betrag>962.22</gesamt-betrag>
            <netto-betrag>808.59</netto-betrag>
            <mehrwert-steuer-betrag>153.63</mehrwert-steuer-betrag>
        </entgelt>
    </rechnung>

    <rechnung>
        <anschrift-des-leistenden-unternehmers>
            <name-unternehmen>Rochaden-La Hoff Pharma GmbH</name-unternehmen>
            <adresse>
                <ort>Grenzye-Wahlen</ort>
                <postleihzahl>79639</postleihzahl>
                <straße>An der Chemie</straße>
                <haus-nummer>17</haus-nummer>
            </adresse>
        </anschrift-des-leistenden-unternehmers>
        <umsatzsteuer-identifikations-nummer>DE333666999</umsatzsteuer-identifikations-nummer>
        <anschrift-des-leistungs-empfängers>
            <name-leistungs-empfänger>
                <vorname>Cypirian</vorname>
                <nachname>Zottel</nachname>
            </name-leistungs-empfänger>
            <adresse>
                <ort>Zottenheim</ort>
                <postleihzahl>13023</postleihzahl>
                <straße>straßestrudel</straße>
                <haus-nummer>5a</haus-nummer>
            </adresse>
        </anschrift-des-leistungs-empfängers>
        <rechnungs-nummer>98-798-7987</rechnungs-nummer>
        <austellungs-datum>
            <tag>8</tag>
            <monat>8</monat>
            <jahr>2017</jahr>
        </austellungs-datum>
        <verwendete-waehrung>Euro</verwendete-waehrung>
        <leistungen>
            <leistung>
                <bezeichnung>Grippemittel "Tumifla"</bezeichnung>
                <menge>3</menge>
                <einzel-preis>120.00</einzel-preis>
                <gesamt-preis>360.00</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>beratung pauschal</bezeichnung>
                <gesamt-preis>50</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>Abführmittel "wech damit" pro liter</bezeichnung>
                <menge>2 liter</menge>
                <einzel-preis>99.99</einzel-preis>
                <gesamt-preis>199.98</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>Energieriegel "Satto"</bezeichnung>
                <menge>2 stück</menge>
                <einzel-preis>5.98</einzel-preis>
                <gesamt-preis>11.96</gesamt-preis>
                <mehrwertsteuer-in-prozent>7</mehrwertsteuer-in-prozent>
            </leistung>
        </leistungen>

        <entgelt>
            <gesamt-betrag>621.94</gesamt-betrag>
            <netto-betrag>490.22</netto-betrag>
            <mehrwert-steuer-betrag>116.74</mehrwert-steuer-betrag>
        </entgelt>

    </rechnung>

    <rechnung>
        <anschrift-des-leistenden-unternehmers>
            <name-unternehmen></name-unternehmen>
            <adresse>
                <ort></ort>
                <postleihzahl></postleihzahl>
                <straße></straße>
                <haus-nummer></haus-nummer>
            </adresse>
        </anschrift-des-leistenden-unternehmers>
        <
        <anschrift-des-leistungs-empfängers>
            <name-leistungs-empfänger>
                <vorname></vorname>
                <nachname></nachname>
            </name-leistungs-empfänger>
            <adresse>
                <ort></ort>
                <postleihzahl></postleihzahl>
                <straße></straße>
                <haus-nummer></haus-nummer>
            </adresse>
        </anschrift-des-leistungs-empfängers>
        <rechnungs-nummer></rechnungs-nummer>
        <austellungs-datum>
            <tag></tag>
            <monat></monat>
            <jahr></jahr>
        </austellungs-datum>
        <verwendete-waehrung></verwendete-waehrung>
        <leistungen>
            <leistung>
                <bezeichnung></bezeichnung>
                <gesamt-preis></gesamt-preis>
                <mehrwertsteuer-in-prozent></mehrwertsteuer-in-prozent>
            </leistung>
        </leistungen>
        <entgelt>
            <gesamt-betrag></gesamt-betrag>
            <netto-betrag></netto-betrag>
            <mehrwert-steuer-betrag></mehrwert-steuer-betrag>
        </entgelt>
    </rechnung>

</rechnungen>
