=== yuri0r/WiSe17_18_DPUE/src/RechnerAufgabe4.xsd
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns="genericNamespace"
        targetNamespace="genericNamespace"
        elementFormDefault="qualified">


    <xs:element name="rechnungen">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="rechnung"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="rechnung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="anschrift-des-leistenden-unternehmers"/>
                <xs:choice>
                    <xs:element ref="steuer-nummer-des-leistenden-unternehmers"/>
                    <xs:element ref="umsatzsteuer-identifikations-nummer"/>
                </xs:choice>
                <xs:element ref="anschrift-des-leistungs-empfaengers"/>
                <xs:element ref="rechnungs-nummer"/>
                <xs:element ref="austellungs-datum"/>
                <xs:element ref="verwendete-waehrung"/>
                <xs:element ref="leistungen"/>
                <xs:element ref="entgelt"/>
                <xs:element ref="bezahl-moeglichkeiten"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="anschrift-des-leistenden-unternehmers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name-unternehmen"/>
                <xs:element minOccurs="0" ref="email-adresse"/>
                <xs:element ref="adresse"/>
                <xs:element minOccurs="0" ref="telefon-nummer"/>
                <xs:element minOccurs="0" ref="fax-nummer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="anschrift-des-leistungs-empfaengers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name-leistungs-empfaenger"/>
                <xs:element ref="adresse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="austellungs-datum">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag"/>
                <xs:element ref="monat"/>
                <xs:element ref="jahr"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="leistungen">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="leistung"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="entgelt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gesamt-betrag"/>
                <xs:element ref="netto-betrag"/>
                <xs:element ref="mehrwert-steuer-betrag"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="adresse">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ort"/>
                <xs:element ref="postleihzahl"/>
                <xs:element ref="strasze"/>
                <xs:element ref="haus-nummer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="name-leistungs-empfaenger">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="anrede"/>
                <xs:element ref="vorname"/>
                <xs:element ref="nachname"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="datum">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag"/>
                <xs:element ref="monat"/>
                <xs:element ref="jahr"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="leistung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bezeichnung"/>
                <xs:element ref="mengen-anzahl" minOccurs="0"/>
                <xs:element ref="mengen-bezeichnung" minOccurs="0"/>
                <xs:element ref="einzel-preis" minOccurs="0"/>
                <xs:element ref="gesamt-preis"/>
                <xs:element ref="mehrwertsteuer-in-prozent"/>
                <xs:element minOccurs="0" ref="datum"/>
            </xs:sequence>
            <xs:attribute name="position"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="bezahl-moeglichkeiten">
        <xs:complexType>
            <xs:all>
                <xs:element ref="bankverbindung" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="bitcoin" minOccurs="0" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="bankverbindung">
        <xs:complexType>
            <xs:all>
                <xs:element ref="iban" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="bic" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="bank" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="konto-nr" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="blz" minOccurs="0" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>


    <xs:element name="email-adresse" type="email-type"/>
    <xs:simpleType name="email-type">
        <xs:restriction base="xs:string">
            <xs:pattern value="(([0-9a-zA-Z.])*[0-9a-zA-Z]+)[@][0-9a-zA-Z]+[.][0-9a-zA-Z]+"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="blz" type="xs:string"/>
    <xs:element name="bitcoin" type="xs:string"/>
    <xs:element name="bic" type="xs:string"/>
    <xs:element name="iban" type="xs:string"/>
    <xs:element name="bank" type="xs:string"/>
    <xs:element name="konto-nr" type="xs:decimal"/>
    <xs:element name="name-unternehmen" type="xs:string"/>
    <xs:element name="ort" type="xs:string"/>
    <xs:element name="postleihzahl" type="xs:string"/>
    <xs:element name="strasze" type="xs:string"/>
    <xs:element name="haus-nummer" type="xs:string"/>
    <xs:element name="telefon-nummer" type="xs:decimal"/>
    <xs:element name="fax-nummer" type="xs:decimal"/>
    <xs:element name="steuer-nummer-des-leistenden-unternehmers" type="xs:decimal"/>
    <xs:element name="anrede" type="xs:string"/>
    <xs:element name="vorname" type="xs:string"/>
    <xs:element name="nachname" type="xs:string"/>
    <xs:element name="rechnungs-nummer" type="xs:string"/>
    <xs:element name="tag" type="xs:decimal"/>
    <xs:element name="monat" type="xs:decimal"/>
    <xs:element name="jahr" type="xs:decimal"/>
    <xs:element name="bezeichnung" type="xs:string"/>
    <xs:element name="mengen-anzahl" type="xs:decimal"/>
    <xs:element name="mengen-bezeichnung" type="xs:string"/>
    <xs:element name="einzel-preis" type="xs:decimal"/>
    <xs:element name="gesamt-preis" type="xs:decimal"/>
    <xs:element name="mehrwertsteuer-in-prozent" type="xs:decimal"/>
    <xs:element name="gesamt-betrag" type="xs:decimal"/>
    <xs:element name="netto-betrag" type="xs:decimal"/>
    <xs:element name="mehrwert-steuer-betrag" type="xs:decimal"/>
    <xs:element name="umsatzsteuer-identifikations-nummer" type="xs:string"/>
    <xs:element name="verwendete-waehrung" type="xs:string"/>
</xs:schema>

=== yuri0r/WiSe17_18_DPUE/src/RechnerAufgabe4.xml
<?xml version = "1.0" encoding ="UTF-8"?>

<rechnungen
        xmlns = "genericNamespace"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="genericNamespace RechnerAufgabe4.xsd">

    <rechnung>
        <anschrift-des-leistenden-unternehmers>
            <name-unternehmen>Kleintier Meier GmbH</name-unternehmen>
            <email-adresse>klein.meier@tiere.de</email-adresse>
            <adresse>
                <ort>Machthausen</ort>
                <postleihzahl>81828</postleihzahl>
                <strasze>Meierring</strasze>
                <haus-nummer>3</haus-nummer>
            </adresse>
            <telefon-nummer>077987987</telefon-nummer>
            <fax-nummer>0777987789</fax-nummer>
        </anschrift-des-leistenden-unternehmers>
        <steuer-nummer-des-leistenden-unternehmers>8812382822</steuer-nummer-des-leistenden-unternehmers>
        <anschrift-des-leistungs-empfaengers>
            <name-leistungs-empfaenger>
                <vorname>Sybille</vorname>
                <nachname>Sonder-Suttelrau</nachname>
            </name-leistungs-empfaenger>
            <adresse>
                <ort>Siedelsuderstadt</ort>
                <postleihzahl>77070</postleihzahl>
                <strasze>Am Suettelbach</strasze>
                <haus-nummer>17</haus-nummer>
            </adresse>
        </anschrift-des-leistungs-empfaengers>
        <rechnungs-nummer>657321</rechnungs-nummer>
        <austellungs-datum>
            <tag>15</tag>
            <monat>1</monat>
            <jahr>2017</jahr>
        </austellungs-datum>
        <verwendete-waehrung>euro</verwendete-waehrung>
        <leistungen>
            <leistung position="1">
                <bezeichnung>Antike Holzwuermer</bezeichnung>
                <menge>100</menge>
                <einzel-preis>1.50</einzel-preis>
                <gesamt-preis>150.00</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
                <datum>
                    <tag>1</tag>
                    <monat>1</monat>
                    <jahr>2017</jahr>
                </datum>
            </leistung>
            <leistung position="2">
                <bezeichnung>Holzwurmfutter</bezeichnung>
                <menge>1</menge>
                <einzel-preis>34.45</einzel-preis>
                <gesamt-preis>34.45</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
                <datum>
                    <tag>12</tag>
                    <monat>1</monat>
                    <jahr>2017</jahr>
                </datum>
            </leistung>
            <leistung position="3">
                <bezeichnung>Steinlaus Petrophaga lorioti</bezeichnung>
                <menge>1</menge>
                <einzel-preis>777.77</einzel-preis>
                <gesamt-preis>777.77</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
                <datum>
                    <tag>12</tag>
                    <monat>1</monat>
                    <jahr>2017</jahr>
                </datum>
            </leistung>
        </leistungen>
        <entgelt>
            <gesamt-betrag>962.22</gesamt-betrag>
            <netto-betrag>808.59</netto-betrag>
            <mehrwert-steuer-betrag>153.63</mehrwert-steuer-betrag>
        </entgelt>
        <bezahl-moeglichkeiten>
            <bankverbindung>
                <bank>sparkasse karlsruhe</bank>
                <konto-nr>3568435456</konto-nr>
                <blz>de 5435764</blz>
            </bankverbindung>
            <bitcoin></bitcoin>
        </bezahl-moeglichkeiten>
    </rechnung>

    <rechnung>
        <anschrift-des-leistenden-unternehmers>
            <name-unternehmen>Rochaden-La Hoff Pharma GmbH</name-unternehmen>
            <adresse>
                <ort>Grenzye-Wahlen</ort>
                <postleihzahl>79639</postleihzahl>
                <strasze>An der Chemie</strasze>
                <haus-nummer>17</haus-nummer>
            </adresse>
        </anschrift-des-leistenden-unternehmers>
        <umsatzsteuer-identifikations-nummer>DE333666999</umsatzsteuer-identifikations-nummer>
        <anschrift-des-leistungs-empfaengers>
            <name-leistungs-empfaenger>
                <vorname>Cypirian</vorname>
                <nachname>Zottel</nachname>
            </name-leistungs-empfaenger>
            <adresse>
                <ort>Zottenheim</ort>
                <postleihzahl>13023</postleihzahl>
                <strasze>straßestrudel</strasze>
                <haus-nummer>5a</haus-nummer>
            </adresse>
        </anschrift-des-leistungs-empfaengers>
        <rechnungs-nummer>98-798-7987</rechnungs-nummer>
        <austellungs-datum>
            <tag>8</tag>
            <monat>8</monat>
            <jahr>2017</jahr>
        </austellungs-datum>
        <verwendete-waehrung>Euro</verwendete-waehrung>
        <leistungen>
            <leistung>
                <bezeichnung>Grippemittel "Tumifla"</bezeichnung>
                <menge>3</menge>
                <einzel-preis>120.00</einzel-preis>
                <gesamt-preis>360.00</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>beratung pauschal</bezeichnung>
                <gesamt-preis>50</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>Abfuehrmittel "wech damit" pro liter</bezeichnung>
                <menge>2 liter</menge>
                <einzel-preis>99.99</einzel-preis>
                <gesamt-preis>199.98</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>Energieriegel "Satto"</bezeichnung>
                <menge>2 stueck</menge>
                <einzel-preis>5.98</einzel-preis>
                <gesamt-preis>11.96</gesamt-preis>
                <mehrwertsteuer-in-prozent>7</mehrwertsteuer-in-prozent>
            </leistung>
        </leistungen>

        <entgelt>
            <gesamt-betrag>621.94</gesamt-betrag>
            <netto-betrag>490.22</netto-betrag>
            <mehrwert-steuer-betrag>116.74</mehrwert-steuer-betrag>
        </entgelt>

        <bezahl-moeglichkeiten>
            <bankverbindung>
                <bank>deutsche bank loerrach</bank>
                <iban>5436453643514654</iban>
                <bic>DE4564655</bic>
            </bankverbindung>
        </bezahl-moeglichkeiten>
    </rechnung>

    <rechnung>
        <anschrift-des-leistenden-unternehmers>
            <name-unternehmen>bestatter uttenberg</name-unternehmen>
            <adresse>
                <ort>ultersingen</ort>
                <postleihzahl>55215</postleihzahl>
                <strasze>oberbergweg</strasze>
                <haus-nummer>5</haus-nummer>
            </adresse>
        </anschrift-des-leistenden-unternehmers>
        <umsatzsteuer-identifikations-nummer>DE6435458435454354</umsatzsteuer-identifikations-nummer>
        <anschrift-des-leistungs-empfaengers>
            <name-leistungs-empfaenger>
                <vorname>Familie</vorname>
                <nachname>Urmel</nachname>
            </name-leistungs-empfaenger>
            <adresse>
                <ort>ultersingen</ort>
                <postleihzahl>58168</postleihzahl>
                <strasze>ulternstarße</strasze>
                <haus-nummer>764</haus-nummer>
            </adresse>
        </anschrift-des-leistungs-empfaengers>
        <rechnungs-nummer>58632125</rechnungs-nummer>
        <austellungs-datum>
            <tag>19</tag>
            <monat>7</monat>
            <jahr>2017</jahr>
        </austellungs-datum>
        <verwendete-waehrung></verwendete-waehrung>
        <leistungen>
            <leistung>
                <bezeichnung>urne eiche massive</bezeichnung>
                <gesamt-preis>299.99</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>ueberfuerung krematorium</bezeichnung>
                <gesamt-preis>349.00</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>dekoration</bezeichnung>
                <gesamt-preis>149.50</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
            <leistung>
                <bezeichnung>trauerkarten</bezeichnung>
                <menge>40</menge>
                <einzel-preis>20.00</einzel-preis>
                <gesamt-preis>80.00</gesamt-preis>
                <mehrwertsteuer-in-prozent>19</mehrwertsteuer-in-prozent>
            </leistung>
        </leistungen>
        <entgelt>
            <gesamt-betrag>878.49</gesamt-betrag>
            <netto-betrag>783.23</netto-betrag>
            <mehrwert-steuer-betrag>140.26</mehrwert-steuer-betrag>
        </entgelt>
        <bezahl-moeglichkeiten>
            <bankverbindung>
                <iban>6845486545648</iban>
                <bank>UBS zuerich</bank>
            </bankverbindung>
            <bitcoin>zgauwzeuokawfeGDZIWHBALDVGkjbhawudvhkaw56465</bitcoin>
        </bezahl-moeglichkeiten>
    </rechnung>
    
    <rechnung>
        <anschrift-des-leistenden-unternehmers>
            <name-unternehmen>Weinhandel von Langres</name-unternehmen>
            <adresse>
                <ort>Mickhausen</ort>
                <postleihzahl>86866</postleihzahl>
                <strasze>Emilianigasse</strasze>
                <haus-nummer>19</haus-nummer>
            </adresse>
        </anschrift-des-leistenden-unternehmers>
